project_id = "mxawkvbwtxikircvecih"

[functions.create-payment]
verify_jwt = false

[functions.admin-serials]
verify_jwt = false

[functions.fulfill-purchase]
verify_jwt = false

[functions.generate-episode]
verify_jwt = false



[functions.gsc-analytics]
verify_jwt = false

[functions.gsc-coverage]
verify_jwt = false

[functions.stripe-stats]
verify_jwt = false
