import { motion } from "framer-motion";
import { TrendingUp, Users, Zap, Globe, Bot, BarChart3, DollarSign, Handshake } from "lucide-react";
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { useEffect, useState } from "react";

const revenueData = [
  { month: "Jan", merch: 2400, digital: 1800, licensing: 5000 },
  { month: "Feb", merch: 3200, digital: 2400, licensing: 5500 },
  { month: "Mar", merch: 4100, digital: 3100, licensing: 7200 },
  { month: "Apr", merch: 5800, digital: 4200, licensing: 9100 },
  { month: "May", merch: 7200, digital: 5800, licensing: 12000 },
  { month: "Jun", merch: 9400, digital: 7600, licensing: 15800 },
];

const streams = [
  { label: "Digital Content", value: "$7,600", growth: "+31%", icon: Zap, color: "text-primary" },
  { label: "Merchandise", value: "$9,400", growth: "+28%", icon: DollarSign, color: "text-emerald-400" },
  { label: "Licensing", value: "$15,800", growth: "+25%", icon: Handshake, color: "text-blue-400" },
  { label: "Partnerships", value: "$4,200", growth: "+42%", icon: Users, color: "text-purple-400" },
];

const pipeline = [
  { stage: "Outreach", count: 142, width: "100%" },
  { stage: "In Contact", count: 67, width: "47%" },
  { stage: "Negotiating", count: 23, width: "16%" },
  { stage: "Signed", count: 12, width: "8%" },
];

const contentEngine = [
  { type: "Lore Entries", produced: 847, tool: "GPT-4 + Claude" },
  { type: "Case File Art", produced: 312, tool: "Midjourney + DALL·E" },
  { type: "Social Posts", produced: 1204, tool: "Claude + Automation" },
  { type: "Video Scripts", produced: 48, tool: "Claude + Remotion" },
];

function AnimatedCounter({ target, suffix = "" }: { target: number; suffix?: string }) {
  const [count, setCount] = useState(0);
  useEffect(() => {
    const duration = 2000;
    const steps = 60;
    const increment = target / steps;
    let current = 0;
    const timer = setInterval(() => {
      current += increment;
      if (current >= target) {
        setCount(target);
        clearInterval(timer);
      } else {
        setCount(Math.floor(current));
      }
    }, duration / steps);
    return () => clearInterval(timer);
  }, [target]);
  return <>{count.toLocaleString()}{suffix}</>;
}

function AiBadge({ tool }: { tool: string }) {
  return (
    <span className="inline-flex items-center gap-1 text-[10px] text-primary/60 bg-primary/5 border border-primary/10 rounded px-1.5 py-0.5">
      <Bot className="w-3 h-3" /> {tool}
    </span>
  );
}

export default function Command() {
  return (
    <div className="min-h-screen bg-background font-body pt-14">
      <div className="max-w-6xl mx-auto px-6 py-16">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-16"
        >
          <div className="flex items-center gap-2 mb-2">
            <p className="text-primary font-display tracking-[0.3em]">AI COMMAND CENTER</p>
            <AiBadge tool="Lovable" />
          </div>
          <h1 className="font-display text-6xl md:text-7xl text-foreground mb-4">BUSINESS DASHBOARD</h1>
          <p className="text-muted-foreground max-w-xl">
            Real-time overview of NakeKnight™ as an AI-powered business. Every metric, every asset,
            every deal — managed and generated by artificial intelligence.
          </p>
        </motion.div>

        {/* Revenue Streams */}
        <section className="mb-16">
          <div className="flex items-center gap-2 mb-6">
            <h2 className="font-display text-3xl text-foreground">REVENUE STREAMS</h2>
            <AiBadge tool="Analytics AI" />
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
            {streams.map((s, i) => (
              <motion.div
                key={s.label}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }}
                className="p-5 bg-card border border-border rounded-lg"
              >
                <s.icon className={`w-5 h-5 ${s.color} mb-3`} />
                <div className="font-display text-3xl text-foreground">{s.value}</div>
                <div className="text-sm text-muted-foreground">{s.label}</div>
                <div className="text-xs text-emerald-400 mt-1">{s.growth} this month</div>
              </motion.div>
            ))}
          </div>

          {/* Chart */}
          <div className="bg-card border border-border rounded-lg p-6">
            <ResponsiveContainer width="100%" height={280}>
              <AreaChart data={revenueData}>
                <CartesianGrid strokeDasharray="3 3" stroke="hsl(25 15% 20%)" />
                <XAxis dataKey="month" stroke="hsl(30 10% 55%)" fontSize={12} />
                <YAxis stroke="hsl(30 10% 55%)" fontSize={12} />
                <Tooltip
                  contentStyle={{
                    background: "hsl(20 12% 12%)",
                    border: "1px solid hsl(25 15% 20%)",
                    borderRadius: "8px",
                    color: "hsl(35 30% 90%)",
                  }}
                />
                <Area type="monotone" dataKey="licensing" stackId="1" stroke="hsl(217 91% 60%)" fill="hsl(217 91% 60% / 0.3)" />
                <Area type="monotone" dataKey="merch" stackId="1" stroke="hsl(142 71% 45%)" fill="hsl(142 71% 45% / 0.3)" />
                <Area type="monotone" dataKey="digital" stackId="1" stroke="hsl(32 90% 55%)" fill="hsl(32 90% 55% / 0.3)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </section>

        {/* Partnership Pipeline */}
        <section className="mb-16">
          <div className="flex items-center gap-2 mb-6">
            <h2 className="font-display text-3xl text-foreground">PARTNERSHIP PIPELINE</h2>
            <AiBadge tool="CRM AI" />
          </div>
          <div className="bg-card border border-border rounded-lg p-6 space-y-4">
            {pipeline.map((p, i) => (
              <motion.div
                key={p.stage}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.15 }}
              >
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-foreground font-display tracking-wider">{p.stage}</span>
                  <span className="text-primary font-display text-lg"><AnimatedCounter target={p.count} /></span>
                </div>
                <div className="h-2 bg-muted rounded-full overflow-hidden">
                  <motion.div
                    className="h-full bg-gradient-to-r from-primary to-primary/60 rounded-full"
                    initial={{ width: 0 }}
                    animate={{ width: p.width }}
                    transition={{ duration: 1.2, delay: i * 0.15 }}
                  />
                </div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* Content Engine */}
        <section className="mb-16">
          <div className="flex items-center gap-2 mb-6">
            <h2 className="font-display text-3xl text-foreground">CONTENT ENGINE</h2>
            <AiBadge tool="Generative AI" />
          </div>
          <div className="grid md:grid-cols-2 gap-4">
            {contentEngine.map((c, i) => (
              <motion.div
                key={c.type}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }}
                className="p-5 bg-card border border-border rounded-lg flex items-center justify-between"
              >
                <div>
                  <div className="font-display text-xl text-foreground">{c.type}</div>
                  <AiBadge tool={c.tool} />
                </div>
                <div className="font-display text-4xl text-primary">
                  <AnimatedCounter target={c.produced} />
                </div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* Community Pulse */}
        <section className="mb-16">
          <div className="flex items-center gap-2 mb-6">
            <h2 className="font-display text-3xl text-foreground">COMMUNITY PULSE</h2>
            <AiBadge tool="Social AI" />
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { label: "Social Followers", value: 24800, icon: Users },
              { label: "Monthly Reach", value: 182000, icon: Globe },
              { label: "Engagement Rate", value: 8.4, icon: TrendingUp, suffix: "%" },
              { label: "Community Score", value: 94, icon: BarChart3, suffix: "/100" },
            ].map((m, i) => (
              <motion.div
                key={m.label}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }}
                className="p-5 bg-card border border-border rounded-lg text-center"
              >
                <m.icon className="w-5 h-5 text-primary mx-auto mb-2" />
                <div className="font-display text-3xl text-foreground">
                  <AnimatedCounter target={m.value} suffix={m.suffix} />
                </div>
                <div className="text-xs text-muted-foreground mt-1">{m.label}</div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* Built With AI Banner */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="text-center p-8 bg-card border border-primary/20 rounded-lg"
        >
          <Bot className="w-8 h-8 text-primary mx-auto mb-3" />
          <h3 className="font-display text-2xl text-foreground mb-2">100% AI-POWERED</h3>
          <p className="text-muted-foreground text-sm max-w-md mx-auto">
            Every metric on this dashboard, every piece of content in the engine, and every
            line of code on this site was created using artificial intelligence.
          </p>
        </motion.div>
      </div>
    </div>
  );
}
